# Generated by Django 3.2.5 on 2021-08-01 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210729_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.manufacturer', verbose_name='Проиводитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mass',
            field=models.IntegerField(default=0, verbose_name='Масса'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/img', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Ширина'),
        ),
    ]
