# Generated by Django 3.2.5 on 2021-08-02 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='сustomer',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='сustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
