# Generated by Django 3.2.5 on 2021-08-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210802_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='musite/store/static/img', verbose_name='Фото'),
        ),
    ]
