# Generated by Django 3.2.5 on 2021-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='musite/media/store/img', verbose_name='Фото'),
        ),
    ]
