# Generated by Django 3.2.5 on 2021-08-06 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='сustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
