# Generated by Django 3.2.5 on 2021-08-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='сustomer',
            new_name='customer',
        ),
    ]
