# Generated by Django 3.2.5 on 2021-09-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_сustomer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
